### ISSUE TITLE
Gate D48....?

### ISSUE THREAD

**Issue by daveroverts** [RickWieman/EHAMGates#23]
Does that gate even exist? If so then I do need glasses!
http://puu.sh/gBDZd/2e0953688c.png
http://puu.sh/gBEaG/345ddf0143.png

**Comment by RickWieman** [comment]
Perhaps @SBlauw can shine his light on this?

According to the AIP, this gate actually *does* exist:
![screen shot 2015-03-15 at 22 42 00](https://cloud.githubusercontent.com/assets/1265791/6658289/9ee30044-cb64-11e4-9565-66fbb107b96f.png)

**Comment by tyrope** [comment]
On euroscope it's hard to read whether that gate was D48 or D46. Apparently both @daveroverts and I read it wrong. ;)

**Comment by daveroverts** [comment]
It's D46 in the TWR sector file
http://puu.sh/gCrU2/9e5c3cfe24.png

**Comment by SBlauw** [comment]
Will be fixed in the next update.

2015-03-16 8:53 GMT+01:00 Dave Roverts <notifications@github.com>:

**Comment by RickWieman** [comment]
Closing this, as the bug does not lie within the gate planner :wink:
