### ISSUE TITLE
Commands don't always register

### ISSUE THREAD

**Issue by tyrope** [RickWieman/EHAMGates#24]
When clicking on certain buttons, for example "?callsign=KLM1694&assign", it doesn't always register... It'll either show to be registered, but then when you switch to All gates they're free, or with an F5 he gets unassigned.

Especially noticeable when setting a user-defined gate, since the drop-down always appears, but not always registers.

**Comment by RickWieman** [comment]
Nice catch! Apparently, the server was running multiple Docker containers containing the gateplanner. What you saw was the work of the nginx proxy: traffic got distributed over the various instances, while the assignments are stored per container (through sessions). Hopefully, I stopped all the double instances now, leaving the latest version of the tool online. Thanks for reporting.
