### ISSUE TITLE
Automatically assign GA to small aircraft

### ISSUE THREAD

**Issue by RickWieman** [RickWieman/EHAMGates#27]
Small aircraft (e.g. C152, C172) with an IFR flight plan could also be marked GA automatically. For this, we'll need ICAO codes of those small aircraft. At first, I though about checking whether the aircraft is cat. 1 or 2, if so, assign GA. However, I just discovered F50 is also cat. 2, so this is probably a bad idea. Perhaps we should create a separate list of aircraft that holds all (usually) GA aircraft?

Via Johan D.

**Comment by daveroverts** [comment]
You could give me a template and let me make a list. You could also add all cat. 2 aircraft and make another list so some aircraft are not allowed.

**Comment by RickWieman** [comment]
I'm a bit in doubt here, but I think I still prefer the first approach: let's add a list of all aircraft that should be marked GA initially.

@daveroverts, I'm looking forward to your contribution!
You can add something like this to the `definitions_global.php` file (preferably near the `aircraftCategories` array):

```php
private static $generalAviationAircraft = array(
  'C152',
  'C172',
  // et cetera
  // NB: the last entry should not end with a comma (,)
);
```

I can then later on use that array for the rest of the implementation. If you know some common mistakes for the various aircraft types, you can also add those to the `invalidAircraftTypeMapping` array, but this could also be future work. I'll leave it up to you :wink:
Thanks a lot!

**Comment by daveroverts** [comment]
Just added all Cessna aircraft 2e13d3fd39f767551ca236c9c61f7b73354c2851. I'll make a pull request when I've added all GA aircraft.

**Comment by RickWieman** [comment]
Cool! Good work :+1:
